{
 "title": "Monitoring Backend",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"monitoring-backend-service\"}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"monitoring-backend-service\"}[5m])"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"monitoring-backend-service\"}"
    }
   ]
  }
 ]
}