apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monitoring-backend
  template:
    metadata:
      labels:
        app: monitoring-backend
    spec:
      serviceAccountName: monitoring-backend
      containers:
      - name: monitoring-backend
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes,gke,production"
        - name: ENVIRONMENT
          value: "gke"
        - name: PLATFORM
          value: "gcp"
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
