include:
  - local: 'shared/variables/global.yml'
  - local: 'shared/variables/computed.yml'
  # template springboot incluse
  - local: 'templates/spring-boot/.gitlab-ci-spring-boot.yml'
  - local: 'shared/variables/dev.yml'
  - local: 'shared/variables/prod.yml'
  - local: 'shared/variables/gke.yml'
  - local: 'templates/platforms/minikube-dev.yml'
  - local: 'templates/platforms/k3s-staging.yml'
  - local: 'templates/integrations/monitoring/prometheus-grafana.yml'
  - local: 'templates/platforms/gke-production.yml'

# Spécifiques au projet (override minimal)
variables:
  APP_NAME: "monitoring-backend"
  APP_PORT: "9090"
  # Sonar
  SONAR_PROJECT_KEY: "monitoring-backend"
  SONAR_PROJECT_NAME: "monitoring-backend"
  # Cosign
  PROJECT_CERT_IDENTITY: "hatemnbouali111000@gmail.com"