apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-backend-deployment
  labels:
    app: monitoring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-backend
  template:
    metadata:
      labels:
        app: monitoring-backend
    spec:
      containers:
      - name: monitoring-backend
        image: hatemnefzi/monitoring-backend:latest
        imagePullPolicy: Always # Use this for local development
        ports:
        - containerPort: 9090
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        # Add any other environment variables your backend needs
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"