apiVersion: v1
kind: Service
metadata:
  name: monitoring-backend-canary-service
  namespace: monitoring-backend
spec:
  selector:
    app: monitoring-backend
    track: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
