apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-backend-ingress
  namespace: monitoring-backend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-ingress-class: "nginx"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - monitoring-backend.duckdns.org
      secretName: monitoring-backend-tls
  rules:
    - host: monitoring-backend.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-backend-service
                port:
                  number: 80
          - path: /canary  # Canary path for monitoring backend
            pathType: Prefix
            backend:
              service:
                name: monitoring-backend-canary-service
                port:
                  number: 80 
