# K3s production — provide K3S_* (server/certs/keys) as CI masked vars
variables:
  ENVIRONMENT_PRODUCTION: "production"
  PROMETHEUS_PRODUCTION_URL: "http://prometheus.production.local"
  GRAFANA_PRODUCTION_URL: "http://grafana.production.local"
  # K3S_* en CI vars : K3S_SERVER, K3S_CA_CERT, K3S_CLIENT_CERT, K3S_CLIENT_KEY
