apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
  labels:
    app: prometheus
data:
  always-alert.rules.yaml: |
    groups:
      - name: AlwaysFire
        rules:
          - alert: AlwaysFiring
            expr: vector(1)
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "This is a test alert"
              description: "This alert always fires to test Alertmanager integration"
