apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - ../../monitoring  
  - ../../ingress/production-ingress.yaml

patchesStrategicMerge:
  - patches/deployment-patch.yaml

images:
  - name: monitoring-backend
    newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-monitoring
    newTag: latest



commonLabels:
  environment: production

configMapGenerator:
  - name: monitoring-backend-config
    behavior: merge
    literals:
      - LOG_LEVEL=WARN
      - ENVIRONMENT=production
      - SERVER_PORT=9090