apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ../../base
- ../../monitoring
- ingress.yaml
  


# ❌ REMOVE THIS ENTIRE SECTION - CI will handle it
# images:
#   - name: monitoring-backend
#     newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-monitoring
#     newTag: latest

# bad commit for demo purposes only


configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL=WARN
  - ENVIRONMENT=production
  - SERVER_PORT=9090
  name: monitoring-backend-config
labels:
- includeSelectors: true
  pairs:
    environment: production
patches:
- path: patches/deployment-patch.yaml
- path: patches/cluster-rolebinding-patch.yaml
images:
- name: monitoring-backend
  newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-monitoring
  newTag: df39614f
