apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-backend
  labels:
    app: monitoring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-backend
  template:
    metadata:
      labels:
        app: monitoring-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        runAsNonRoot: true
        fsGroup: 2000

      imagePullSecrets:
        - name: gitlab-registry-secret
      volumes:
        - name: tmp-volume
          emptyDir: {}  # 🔒 Volume temporaire pour /tmp
      containers:
        - name: monitoring-backend
          image: monitoring-backend:1.0.0  # Remplacé par kustomize
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SERVER_PORT
              value: "9090"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp  # 🔥 Permet à l'app d’écrire dans /tmp
