apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: monitoring-backend-base

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - rbac/service-account.yaml
  - rbac/cluster-role.yaml
  - rbac/cluster-role-binding.yaml
  # - deployment-canary.yaml # Canary deployment for monitoring backend

commonLabels:
  app: monitoring-backend
  component: backend
  part-of: monitoring-system

images:
  - name: monitoring-backend
   

#configMapGenerator:
 # - name: monitoring-backend-config
  #  literals:
   #   - LOG_LEVEL=INFO
    #  - SERVER_PORT=9090  , removed to ensure no duplicat configmap