apiVersion: v1
kind: Service
metadata:
  name: monitoring-backend-service
  annotations:
    cloud.google.com/neg: '{"ingress":true}' # Enable NEG for GKE Ingress
  labels:
    app: monitoring-backend
spec:
  selector:
    app: monitoring-backend
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
  type: ClusterIP