apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
patches:
  - path: patches/deployment-patch.yaml
images:
  - name: monitoring-backend
    newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-monitoring
    newTag: latest

    
labels:
  - pairs:
      environment: staging
configMapGenerator:
  - name: monitoring-backend-config
    behavior: replace
    literals:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=staging
      - SERVER_PORT=9090