apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization  #namespace: staging  removing namespace for testign purposes 
resources:
- ../../base
  
patches:
- path: patches/deployment-patch.yaml
- path: patches/cluster-rolebinding-patch.yaml

images:
- name: monitoring-backend
  newName: registry.proxiad-axe-seine.com/proxiad-academie/ops-monitoring
  newTag: latest

    
configMapGenerator:
- behavior: replace
  literals:
  - LOG_LEVEL=DEBUG
  - ENVIRONMENT=staging
  - SERVER_PORT=9090
  name: monitoring-backend-config
